# Generated by Django 5.1.5 on 2025-03-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpurchaseorder',
            old_name='total_amount',
            new_name='total_value',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='total_amount',
            new_name='total_value',
        ),
    ]
