# Generated by Django 5.1.5 on 2025-03-18 15:22

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('store_name', 'Store Name'), ('default_currency', 'Default Currency'), ('tax_rate', 'Default Tax Rate (%)')], max_length=255, unique=True, verbose_name='Setting Key')),
                ('value', models.TextField(help_text='Value of the setting. Data type depends on the setting key.', verbose_name='Setting Value')),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('decimal', 'Decimal'), ('json', 'JSON')], default='string', help_text='Data type of the setting value', max_length=50, verbose_name='Data Type')),
                ('description', models.TextField(blank=True, help_text='Description of what this setting controls (optional)', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Setting',
                'verbose_name_plural': 'Store Settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalStoreSetting',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('key', models.CharField(choices=[('store_name', 'Store Name'), ('default_currency', 'Default Currency'), ('tax_rate', 'Default Tax Rate (%)')], db_index=True, max_length=255, verbose_name='Setting Key')),
                ('value', models.TextField(help_text='Value of the setting. Data type depends on the setting key.', verbose_name='Setting Value')),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('decimal', 'Decimal'), ('json', 'JSON')], default='string', help_text='Data type of the setting value', max_length=50, verbose_name='Data Type')),
                ('description', models.TextField(blank=True, help_text='Description of what this setting controls (optional)', verbose_name='Description')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Store Setting',
                'verbose_name_plural': 'historical Store Settings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
