# Generated by Django 5.1.5 on 2025-02-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaletransaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('voided', 'Voided')], default='completed', help_text='Indicates whether the sale is completed or voided', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('voided', 'Voided')], default='completed', help_text='Indicates whether the sale is completed or voided', max_length=20, verbose_name='Status'),
        ),
    ]
