# Generated by Django 5.1.5 on 2025-03-09 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_historicalsaletransaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsaleitem',
            name='sale_transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, default=uuid.uuid4, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.saletransaction', verbose_name='Sale Transaction'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale_transaction',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='sales.saletransaction', verbose_name='Sale Transaction'),
        ),
    ]
