# Generated by Django 5.2 on 2025-09-02 17:44

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Brand Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description for the brand",
                        verbose_name="Description",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Optional brand logo image",
                        upload_to="brand_logos/",
                        verbose_name="Logo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Category Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description for the category",
                        verbose_name="Description",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalProductExpiration",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        help_text="Batch or lot number for tracking",
                        max_length=100,
                        verbose_name="Batch/Lot Number",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Quantity in this batch", verbose_name="Quantity"
                    ),
                ),
                ("manufacture_date", models.DateField(verbose_name="Manufacture Date")),
                ("expiration_date", models.DateField(verbose_name="Expiration Date")),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit for this batch",
                        max_digits=10,
                        verbose_name="Unit Cost",
                    ),
                ),
                (
                    "is_expired",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this batch has expired",
                        verbose_name="Is Expired",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Product Expiration",
                "verbose_name_plural": "historical Product Expirations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProductImage",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "image",
                    models.TextField(
                        help_text="Product image file",
                        max_length=100,
                        verbose_name="Image",
                    ),
                ),
                (
                    "is_thumbnail",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this image is the thumbnail for the product",
                        verbose_name="Is Thumbnail",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Product Image",
                "verbose_name_plural": "historical Product Images",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProductVariant",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the variant option (e.g., Size, Color)",
                        max_length=255,
                        verbose_name="Variant Option Name",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Value of the variant option (e.g., Large, Red)",
                        max_length=255,
                        verbose_name="Variant Value",
                    ),
                ),
                (
                    "additional_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Additional price for this variant (can be positive or negative)",
                        max_digits=10,
                        verbose_name="Additional Price",
                    ),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="Stock quantity specific to this variant",
                        verbose_name="Variant Stock Quantity",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Product Variant",
                "verbose_name_plural": "historical Product Variants",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalStockAdjustment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "adjustment_id",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        max_length=50,
                        verbose_name="Adjustment ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("count_discrepancy", "Physical Count Discrepancy"),
                            ("damage", "Damaged Goods"),
                            ("theft", "Theft/Loss"),
                            ("expired", "Expired Products"),
                            ("system_error", "System Error Correction"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Adjustment Reason",
                    ),
                ),
                (
                    "quantity_before",
                    models.IntegerField(
                        help_text="Stock quantity before adjustment",
                        verbose_name="Quantity Before",
                    ),
                ),
                (
                    "quantity_after",
                    models.IntegerField(
                        help_text="Stock quantity after adjustment",
                        verbose_name="Quantity After",
                    ),
                ),
                (
                    "adjustment_quantity",
                    models.IntegerField(
                        help_text="Difference in quantity (positive or negative)",
                        verbose_name="Adjustment Quantity",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit for valuation",
                        max_digits=10,
                        verbose_name="Unit Cost",
                    ),
                ),
                (
                    "total_value_impact",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total financial impact of adjustment",
                        max_digits=12,
                        verbose_name="Total Value Impact",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Detailed explanation of the adjustment",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "adjustment_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Adjustment Date",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Stock Adjustment",
                "verbose_name_plural": "historical Stock Adjustments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalStockMovement",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "movement_id",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="Unique identifier for this stock movement",
                        max_length=50,
                        verbose_name="Movement ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase/Stock In"),
                            ("sale", "Sale/Stock Out"),
                            ("adjustment", "Stock Adjustment"),
                            ("transfer_in", "Transfer In"),
                            ("transfer_out", "Transfer Out"),
                            ("return", "Customer Return"),
                            ("damage", "Damage/Loss"),
                            ("expired", "Expired Product"),
                            ("count", "Physical Count Adjustment"),
                        ],
                        max_length=20,
                        verbose_name="Movement Type",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Positive for stock in, negative for stock out",
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit for this movement",
                        max_digits=10,
                        verbose_name="Unit Cost",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total cost of this movement (quantity × unit cost)",
                        max_digits=12,
                        verbose_name="Total Cost",
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference to related transaction (PO, Sale, etc.)",
                        max_length=100,
                        verbose_name="Reference ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this stock movement",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "movement_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Movement Date"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Stock Movement",
                "verbose_name_plural": "historical Stock Movements",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Product Name")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed product description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        db_index=True,
                        help_text="Stock Keeping Unit - unique product identifier",
                        max_length=50,
                        unique=True,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Optional barcode for product scanning",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Barcode",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost price of the product",
                        max_digits=10,
                        verbose_name="Cost Price",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Selling price of the product",
                        max_digits=10,
                        verbose_name="Selling Price",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Tax rate for the product as percentage",
                        max_digits=5,
                        verbose_name="Tax Rate (%)",
                    ),
                ),
                (
                    "unit_of_measurement",
                    models.CharField(
                        default="pieces",
                        help_text="Unit in which product is measured (e.g., pieces, kg, liters)",
                        max_length=50,
                        verbose_name="Unit of Measurement",
                    ),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="Legacy field - use LocationInventory for multi-store support",
                        verbose_name="Stock Quantity (Legacy)",
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.IntegerField(
                        default=10,
                        help_text="Quantity below which low stock alerts are triggered",
                        verbose_name="Low Stock Threshold",
                    ),
                ),
                (
                    "reorder_point",
                    models.IntegerField(
                        default=20,
                        help_text="Stock level at which automatic reorder should be triggered",
                        verbose_name="Reorder Point",
                    ),
                ),
                (
                    "reorder_quantity",
                    models.IntegerField(
                        default=50,
                        help_text="Quantity to order when reorder point is reached",
                        verbose_name="Reorder Quantity",
                    ),
                ),
                (
                    "maximum_stock_level",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum stock level to maintain (optional)",
                        null=True,
                        verbose_name="Maximum Stock Level",
                    ),
                ),
                (
                    "inventory_valuation_method",
                    models.CharField(
                        choices=[
                            ("fifo", "First In, First Out (FIFO)"),
                            ("lifo", "Last In, First Out (LIFO)"),
                            ("average", "Weighted Average Cost"),
                        ],
                        default="fifo",
                        help_text="Method used for inventory cost calculation",
                        max_length=20,
                        verbose_name="Inventory Valuation Method",
                    ),
                ),
                (
                    "is_perishable",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the product has expiration dates",
                        verbose_name="Is Perishable",
                    ),
                ),
                (
                    "shelf_life_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of days product remains fresh (for perishable items)",
                        null=True,
                        verbose_name="Shelf Life (Days)",
                    ),
                ),
                (
                    "average_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Weighted average cost of inventory (calculated automatically)",
                        max_digits=10,
                        verbose_name="Average Cost",
                    ),
                ),
                (
                    "total_inventory_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total value of current inventory (calculated automatically)",
                        max_digits=12,
                        verbose_name="Total Inventory Value",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the product is active and available for sale",
                        verbose_name="Is Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductExpiration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        help_text="Batch or lot number for tracking",
                        max_length=100,
                        verbose_name="Batch/Lot Number",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Quantity in this batch", verbose_name="Quantity"
                    ),
                ),
                ("manufacture_date", models.DateField(verbose_name="Manufacture Date")),
                ("expiration_date", models.DateField(verbose_name="Expiration Date")),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit for this batch",
                        max_digits=10,
                        verbose_name="Unit Cost",
                    ),
                ),
                (
                    "is_expired",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this batch has expired",
                        verbose_name="Is Expired",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product Expiration",
                "verbose_name_plural": "Product Expirations",
                "ordering": ["expiration_date"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Product image file",
                        upload_to="product_images/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "is_thumbnail",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this image is the thumbnail for the product",
                        verbose_name="Is Thumbnail",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the variant option (e.g., Size, Color)",
                        max_length=255,
                        verbose_name="Variant Option Name",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Value of the variant option (e.g., Large, Red)",
                        max_length=255,
                        verbose_name="Variant Value",
                    ),
                ),
                (
                    "additional_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Additional price for this variant (can be positive or negative)",
                        max_digits=10,
                        verbose_name="Additional Price",
                    ),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="Stock quantity specific to this variant",
                        verbose_name="Variant Stock Quantity",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product Variant",
                "verbose_name_plural": "Product Variants",
                "ordering": ["name", "value"],
            },
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adjustment_id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=50,
                        unique=True,
                        verbose_name="Adjustment ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("count_discrepancy", "Physical Count Discrepancy"),
                            ("damage", "Damaged Goods"),
                            ("theft", "Theft/Loss"),
                            ("expired", "Expired Products"),
                            ("system_error", "System Error Correction"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Adjustment Reason",
                    ),
                ),
                (
                    "quantity_before",
                    models.IntegerField(
                        help_text="Stock quantity before adjustment",
                        verbose_name="Quantity Before",
                    ),
                ),
                (
                    "quantity_after",
                    models.IntegerField(
                        help_text="Stock quantity after adjustment",
                        verbose_name="Quantity After",
                    ),
                ),
                (
                    "adjustment_quantity",
                    models.IntegerField(
                        help_text="Difference in quantity (positive or negative)",
                        verbose_name="Adjustment Quantity",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit for valuation",
                        max_digits=10,
                        verbose_name="Unit Cost",
                    ),
                ),
                (
                    "total_value_impact",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total financial impact of adjustment",
                        max_digits=12,
                        verbose_name="Total Value Impact",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Detailed explanation of the adjustment",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "adjustment_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Adjustment Date",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Stock Adjustment",
                "verbose_name_plural": "Stock Adjustments",
                "ordering": ["-adjustment_date"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_id",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="Unique identifier for this stock movement",
                        max_length=50,
                        unique=True,
                        verbose_name="Movement ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase/Stock In"),
                            ("sale", "Sale/Stock Out"),
                            ("adjustment", "Stock Adjustment"),
                            ("transfer_in", "Transfer In"),
                            ("transfer_out", "Transfer Out"),
                            ("return", "Customer Return"),
                            ("damage", "Damage/Loss"),
                            ("expired", "Expired Product"),
                            ("count", "Physical Count Adjustment"),
                        ],
                        max_length=20,
                        verbose_name="Movement Type",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Positive for stock in, negative for stock out",
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit for this movement",
                        max_digits=10,
                        verbose_name="Unit Cost",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total cost of this movement (quantity × unit cost)",
                        max_digits=12,
                        verbose_name="Total Cost",
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference to related transaction (PO, Sale, etc.)",
                        max_length=100,
                        verbose_name="Reference ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this stock movement",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "movement_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Movement Date"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Stock Movement",
                "verbose_name_plural": "Stock Movements",
                "ordering": ["-movement_date"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalBrand",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Brand Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description for the brand",
                        verbose_name="Description",
                    ),
                ),
                (
                    "logo",
                    models.TextField(
                        blank=True,
                        help_text="Optional brand logo image",
                        max_length=100,
                        verbose_name="Logo",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Brand",
                "verbose_name_plural": "historical Brands",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCategory",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Category Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description for the category",
                        verbose_name="Description",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Category",
                "verbose_name_plural": "historical Categories",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProduct",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Product Name")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed product description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        db_index=True,
                        help_text="Stock Keeping Unit - unique product identifier",
                        max_length=50,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Optional barcode for product scanning",
                        max_length=100,
                        null=True,
                        verbose_name="Barcode",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost price of the product",
                        max_digits=10,
                        verbose_name="Cost Price",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Selling price of the product",
                        max_digits=10,
                        verbose_name="Selling Price",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Tax rate for the product as percentage",
                        max_digits=5,
                        verbose_name="Tax Rate (%)",
                    ),
                ),
                (
                    "unit_of_measurement",
                    models.CharField(
                        default="pieces",
                        help_text="Unit in which product is measured (e.g., pieces, kg, liters)",
                        max_length=50,
                        verbose_name="Unit of Measurement",
                    ),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="Legacy field - use LocationInventory for multi-store support",
                        verbose_name="Stock Quantity (Legacy)",
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.IntegerField(
                        default=10,
                        help_text="Quantity below which low stock alerts are triggered",
                        verbose_name="Low Stock Threshold",
                    ),
                ),
                (
                    "reorder_point",
                    models.IntegerField(
                        default=20,
                        help_text="Stock level at which automatic reorder should be triggered",
                        verbose_name="Reorder Point",
                    ),
                ),
                (
                    "reorder_quantity",
                    models.IntegerField(
                        default=50,
                        help_text="Quantity to order when reorder point is reached",
                        verbose_name="Reorder Quantity",
                    ),
                ),
                (
                    "maximum_stock_level",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum stock level to maintain (optional)",
                        null=True,
                        verbose_name="Maximum Stock Level",
                    ),
                ),
                (
                    "inventory_valuation_method",
                    models.CharField(
                        choices=[
                            ("fifo", "First In, First Out (FIFO)"),
                            ("lifo", "Last In, First Out (LIFO)"),
                            ("average", "Weighted Average Cost"),
                        ],
                        default="fifo",
                        help_text="Method used for inventory cost calculation",
                        max_length=20,
                        verbose_name="Inventory Valuation Method",
                    ),
                ),
                (
                    "is_perishable",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the product has expiration dates",
                        verbose_name="Is Perishable",
                    ),
                ),
                (
                    "shelf_life_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of days product remains fresh (for perishable items)",
                        null=True,
                        verbose_name="Shelf Life (Days)",
                    ),
                ),
                (
                    "average_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Weighted average cost of inventory (calculated automatically)",
                        max_digits=10,
                        verbose_name="Average Cost",
                    ),
                ),
                (
                    "total_inventory_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total value of current inventory (calculated automatically)",
                        max_digits=12,
                        verbose_name="Total Inventory Value",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the product is active and available for sale",
                        verbose_name="Is Active",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Optional brand of the product",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="products.brand",
                        verbose_name="Brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Category of the product",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="products.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Product",
                "verbose_name_plural": "historical Products",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
